language: python

python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

variables:
  PIP_CACHE_DIR: .pipenv/pipcache
  WORKON_HOME: .pipenv/venvs

cache:
  key: pipenv
  paths:
    - .pipenv

install:
  - pipenv sync --dev

script:
  - pipenv run pytest --cov=./
  - |  # only need to run black in one environment
    if [[ "${TRAVIS_PYTHON_VERSION}" == "3.7" ]]; then
      pipenv run black -l 120 -t py35 -t py36 -t py37 -t py38 --check meican;
    fi

after_success:
  - |
    if [[ ! -z "${TRAVIS_TAG}" && "${TRAVIS_PYTHON_VERSION}" == "3.7" ]]; then
      pipenv run python setup.py sdist bdist_wheel;
      pipenv run twine upload --skip-existing dist/*;
    fi
